//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbVisionEntities : DbContext
    {
        public dbVisionEntities()
            : base("name=dbVisionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblEmployeeSalaryIncrement> tblEmployeeSalaryIncrements { get; set; }
        public virtual DbSet<tblPAYERelief> tblPAYEReliefs { get; set; }
        public virtual DbSet<tblPAYEReliefRate> tblPAYEReliefRates { get; set; }
        public virtual DbSet<tblPayrollEmployePAYERelief> tblPayrollEmployePAYEReliefs { get; set; }
        public virtual DbSet<tblAccount> tblAccounts { get; set; }
        public virtual DbSet<tblAccountType> tblAccountTypes { get; set; }
        public virtual DbSet<tblBankBranch> tblBankBranches { get; set; }
        public virtual DbSet<tblBankName> tblBankNames { get; set; }
        public virtual DbSet<tblBiometricDevice> tblBiometricDevices { get; set; }
        public virtual DbSet<tblCity> tblCities { get; set; }
        public virtual DbSet<tblCompany> tblCompanies { get; set; }
        public virtual DbSet<tblCountry> tblCountries { get; set; }
        public virtual DbSet<tblCurrency> tblCurrencies { get; set; }
        public virtual DbSet<tblDataReceiverErrorLog> tblDataReceiverErrorLogs { get; set; }
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
        public virtual DbSet<tblEmployeeAccountingLedger> tblEmployeeAccountingLedgers { get; set; }
        public virtual DbSet<tblEmployeeAttendance> tblEmployeeAttendances { get; set; }
        public virtual DbSet<tblEmployeeAttendanceDetail> tblEmployeeAttendanceDetails { get; set; }
        public virtual DbSet<tblEmployeeBMDUpdateLog> tblEmployeeBMDUpdateLogs { get; set; }
        public virtual DbSet<tblEmployeeDepartment> tblEmployeeDepartments { get; set; }
        public virtual DbSet<tblEmployeeDesignation> tblEmployeeDesignations { get; set; }
        public virtual DbSet<tblEmployeeDocument> tblEmployeeDocuments { get; set; }
        public virtual DbSet<tblEmployeeEarningDeduction> tblEmployeeEarningDeductions { get; set; }
        public virtual DbSet<tblEmployeeFamily> tblEmployeeFamilies { get; set; }
        public virtual DbSet<tblEmployeeLeaveOpeningBalance> tblEmployeeLeaveOpeningBalances { get; set; }
        public virtual DbSet<tblEmployeeListFormat> tblEmployeeListFormats { get; set; }
        public virtual DbSet<tblEmployeeNoPrefix> tblEmployeeNoPrefixes { get; set; }
        public virtual DbSet<tblEmployeeRestDay> tblEmployeeRestDays { get; set; }
        public virtual DbSet<tblEmployeeServiceDetail> tblEmployeeServiceDetails { get; set; }
        public virtual DbSet<tblEmployeeShift> tblEmployeeShifts { get; set; }
        public virtual DbSet<tblEmployeeShiftAllocation> tblEmployeeShiftAllocations { get; set; }
        public virtual DbSet<tblEmployeeWIBAClass> tblEmployeeWIBAClasses { get; set; }
        public virtual DbSet<tblEmployeeWIBAClassRate> tblEmployeeWIBAClassRates { get; set; }
        public virtual DbSet<tblEmployementTerminationCause> tblEmployementTerminationCauses { get; set; }
        public virtual DbSet<tblFinPeriod> tblFinPeriods { get; set; }
        public virtual DbSet<tblGridLayout> tblGridLayouts { get; set; }
        public virtual DbSet<tblHoliday> tblHolidays { get; set; }
        public virtual DbSet<tblLeaveAdjustment> tblLeaveAdjustments { get; set; }
        public virtual DbSet<tblLeaveAdjustmentNoPrefix> tblLeaveAdjustmentNoPrefixes { get; set; }
        public virtual DbSet<tblLeaveApplication> tblLeaveApplications { get; set; }
        public virtual DbSet<tblLeaveApplicationDayDetail> tblLeaveApplicationDayDetails { get; set; }
        public virtual DbSet<tblLeaveApplicationNoPrefix> tblLeaveApplicationNoPrefixes { get; set; }
        public virtual DbSet<tblLeaveEncashment> tblLeaveEncashments { get; set; }
        public virtual DbSet<tblLeaveEncashmentNoPrefix> tblLeaveEncashmentNoPrefixes { get; set; }
        public virtual DbSet<tblLeaveType> tblLeaveTypes { get; set; }
        public virtual DbSet<tblLoanAdjustment> tblLoanAdjustments { get; set; }
        public virtual DbSet<tblLoanAdjustmentNoPrefix> tblLoanAdjustmentNoPrefixes { get; set; }
        public virtual DbSet<tblLoanApplication> tblLoanApplications { get; set; }
        public virtual DbSet<tblLoanApplicationNoPrefix> tblLoanApplicationNoPrefixes { get; set; }
        public virtual DbSet<tblLocation> tblLocations { get; set; }
        public virtual DbSet<tblLocationWeekendSetting> tblLocationWeekendSettings { get; set; }
        public virtual DbSet<tblMinimumWageCategory> tblMinimumWageCategories { get; set; }
        public virtual DbSet<tblMinimumWageRate> tblMinimumWageRates { get; set; }
        public virtual DbSet<tblNonCashBenefit> tblNonCashBenefits { get; set; }
        public virtual DbSet<tblPayroll> tblPayrolls { get; set; }
        public virtual DbSet<tblPayrollEmployeeDetail> tblPayrollEmployeeDetails { get; set; }
        public virtual DbSet<tblPayrollEmployeeEarningsDeduction> tblPayrollEmployeeEarningsDeductions { get; set; }
        public virtual DbSet<tblPayrollEmployeeNonCashBenefit> tblPayrollEmployeeNonCashBenefits { get; set; }
        public virtual DbSet<tblRecordState> tblRecordStates { get; set; }
        public virtual DbSet<tblSafariApplication> tblSafariApplications { get; set; }
        public virtual DbSet<tblSafariApplicationDayDetail> tblSafariApplicationDayDetails { get; set; }
        public virtual DbSet<tblSafariApplicationNoPrefix> tblSafariApplicationNoPrefixes { get; set; }
        public virtual DbSet<tblSettingL0> tblSettingL0 { get; set; }
        public virtual DbSet<tblSettingMasterL1> tblSettingMasterL1 { get; set; }
        public virtual DbSet<tblSettingsL1> tblSettingsL1 { get; set; }
        public virtual DbSet<tblSMSLog> tblSMSLogs { get; set; }
        public virtual DbSet<tblState> tblStates { get; set; }
        public virtual DbSet<tblTAApproval> tblTAApprovals { get; set; }
        public virtual DbSet<tblTAApprovalNoPrefix> tblTAApprovalNoPrefixes { get; set; }
        public virtual DbSet<tblTaxSlabDetail> tblTaxSlabDetails { get; set; }
        public virtual DbSet<tblTaxSlabHeader> tblTaxSlabHeaders { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUserGroup> tblUserGroups { get; set; }
        public virtual DbSet<tblUserGroupPerimission> tblUserGroupPerimissions { get; set; }
        public virtual DbSet<tblUserGroupPermissionOnCompany> tblUserGroupPermissionOnCompanies { get; set; }
        public virtual DbSet<tblUserGroupPermissionOnLocation> tblUserGroupPermissionOnLocations { get; set; }
        public virtual DbSet<tblPayrollMonth> tblPayrollMonths { get; set; }
    }
}
