//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAccount()
        {
            this.tblLoanAdjustments = new HashSet<tblLoanAdjustment>();
        }
    
        public int AccountID { get; set; }
        public string AccountName { get; set; }
        public byte AccountType { get; set; }
        public string BankAccountNo { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public Nullable<int> CityID { get; set; }
        public string PIN { get; set; }
        public Nullable<int> BankNameID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public int CompanyID { get; set; }
        public byte rstate { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> reuid { get; set; }
    
        public virtual tblBankBranch tblBankBranch { get; set; }
        public virtual tblBankName tblBankName { get; set; }
        public virtual tblCity tblCity { get; set; }
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblCurrency tblCurrency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoanAdjustment> tblLoanAdjustments { get; set; }
    }
}
