//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBiometricDevice
    {
        public int BMDID { get; set; }
        public string BMDTitle { get; set; }
        public int MachineNo { get; set; }
        public string IPAddress { get; set; }
        public int PortNo { get; set; }
        public int Password { get; set; }
        public int CompanyID { get; set; }
        public byte rstate { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> reuid { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
    }
}
