//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCompany()
        {
            this.tblAccounts = new HashSet<tblAccount>();
            this.tblBiometricDevices = new HashSet<tblBiometricDevice>();
            this.tblEmployees = new HashSet<tblEmployee>();
            this.tblEmployeeAccountingLedgers = new HashSet<tblEmployeeAccountingLedger>();
            this.tblEmployeeAttendances = new HashSet<tblEmployeeAttendance>();
            this.tblEmployeeAttendanceDetails = new HashSet<tblEmployeeAttendanceDetail>();
            this.tblEmployeeDepartments = new HashSet<tblEmployeeDepartment>();
            this.tblEmployeeDesignations = new HashSet<tblEmployeeDesignation>();
            this.tblEmployeeNoPrefixes = new HashSet<tblEmployeeNoPrefix>();
            this.tblEmployeeRestDays = new HashSet<tblEmployeeRestDay>();
            this.tblEmployeeSalaryIncrements = new HashSet<tblEmployeeSalaryIncrement>();
            this.tblEmployeeShifts = new HashSet<tblEmployeeShift>();
            this.tblEmployeeShiftAllocations = new HashSet<tblEmployeeShiftAllocation>();
            this.tblEmployeeWIBAClasses = new HashSet<tblEmployeeWIBAClass>();
            this.tblEmployeeWIBAClassRates = new HashSet<tblEmployeeWIBAClassRate>();
            this.tblFinPeriods = new HashSet<tblFinPeriod>();
            this.tblGridLayouts = new HashSet<tblGridLayout>();
            this.tblHolidays = new HashSet<tblHoliday>();
            this.tblLeaveAdjustments = new HashSet<tblLeaveAdjustment>();
            this.tblLeaveAdjustmentNoPrefixes = new HashSet<tblLeaveAdjustmentNoPrefix>();
            this.tblLeaveApplications = new HashSet<tblLeaveApplication>();
            this.tblLeaveApplicationNoPrefixes = new HashSet<tblLeaveApplicationNoPrefix>();
            this.tblLeaveEncashments = new HashSet<tblLeaveEncashment>();
            this.tblLeaveEncashmentNoPrefixes = new HashSet<tblLeaveEncashmentNoPrefix>();
            this.tblLeaveTypes = new HashSet<tblLeaveType>();
            this.tblLoanAdjustments = new HashSet<tblLoanAdjustment>();
            this.tblLoanAdjustmentNoPrefixes = new HashSet<tblLoanAdjustmentNoPrefix>();
            this.tblLoanApplications = new HashSet<tblLoanApplication>();
            this.tblLoanApplicationNoPrefixes = new HashSet<tblLoanApplicationNoPrefix>();
            this.tblMinimumWageCategories = new HashSet<tblMinimumWageCategory>();
            this.tblNonCashBenefits = new HashSet<tblNonCashBenefit>();
            this.tblPAYEReliefs = new HashSet<tblPAYERelief>();
            this.tblPayrolls = new HashSet<tblPayroll>();
            this.tblSafariApplications = new HashSet<tblSafariApplication>();
            this.tblSafariApplicationNoPrefixes = new HashSet<tblSafariApplicationNoPrefix>();
            this.tblTAApprovals = new HashSet<tblTAApproval>();
            this.tblTAApprovalNoPrefixes = new HashSet<tblTAApprovalNoPrefix>();
            this.tblTaxSlabHeaders = new HashSet<tblTaxSlabHeader>();
            this.tblUserGroupPermissionOnCompanies = new HashSet<tblUserGroupPermissionOnCompany>();
            this.tblPayrollMonths = new HashSet<tblPayrollMonth>();
        }
    
        public int CompanyID { get; set; }
        public int CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public int CityID { get; set; }
        public string PIN { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string MobileNo1 { get; set; }
        public string MobileNo2 { get; set; }
        public string EMailID { get; set; }
        public string Website { get; set; }
        public System.DateTime BusinessStartedFrom { get; set; }
        public string IncorporationNo { get; set; }
        public Nullable<System.DateTime> IncorporationDate { get; set; }
        public string PINNo_RegNo { get; set; }
        public string NSSFNo { get; set; }
        public string NHIFNo { get; set; }
        public string PFNo { get; set; }
        public string SaccoRegNo { get; set; }
        public string Bank1_Name { get; set; }
        public string Bank1_BranchName { get; set; }
        public string Bank1_AccountNo { get; set; }
        public string Bank1_Currency { get; set; }
        public string Bank2_Name { get; set; }
        public string Bank2_BranchName { get; set; }
        public string Bank2_AccountNo { get; set; }
        public string Bank2_Currency { get; set; }
        public string Bank3_Name { get; set; }
        public string Bank3_BranchName { get; set; }
        public string Bank3_AccountNo { get; set; }
        public string Bank3_Currency { get; set; }
        public string CompanyLogoFileName { get; set; }
        public int CurrencyID { get; set; }
        public byte rstate { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> reuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccount> tblAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBiometricDevice> tblBiometricDevices { get; set; }
        public virtual tblCity tblCity { get; set; }
        public virtual tblCurrency tblCurrency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployee> tblEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeAccountingLedger> tblEmployeeAccountingLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeAttendance> tblEmployeeAttendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeAttendanceDetail> tblEmployeeAttendanceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeDepartment> tblEmployeeDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeDesignation> tblEmployeeDesignations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeNoPrefix> tblEmployeeNoPrefixes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeRestDay> tblEmployeeRestDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeSalaryIncrement> tblEmployeeSalaryIncrements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeShift> tblEmployeeShifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeShiftAllocation> tblEmployeeShiftAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeWIBAClass> tblEmployeeWIBAClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeWIBAClassRate> tblEmployeeWIBAClassRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFinPeriod> tblFinPeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGridLayout> tblGridLayouts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHoliday> tblHolidays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeaveAdjustment> tblLeaveAdjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeaveAdjustmentNoPrefix> tblLeaveAdjustmentNoPrefixes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeaveApplication> tblLeaveApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeaveApplicationNoPrefix> tblLeaveApplicationNoPrefixes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeaveEncashment> tblLeaveEncashments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeaveEncashmentNoPrefix> tblLeaveEncashmentNoPrefixes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeaveType> tblLeaveTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoanAdjustment> tblLoanAdjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoanAdjustmentNoPrefix> tblLoanAdjustmentNoPrefixes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoanApplication> tblLoanApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoanApplicationNoPrefix> tblLoanApplicationNoPrefixes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMinimumWageCategory> tblMinimumWageCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNonCashBenefit> tblNonCashBenefits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPAYERelief> tblPAYEReliefs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPayroll> tblPayrolls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSafariApplication> tblSafariApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSafariApplicationNoPrefix> tblSafariApplicationNoPrefixes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTAApproval> tblTAApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTAApprovalNoPrefix> tblTAApprovalNoPrefixes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTaxSlabHeader> tblTaxSlabHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserGroupPermissionOnCompany> tblUserGroupPermissionOnCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPayrollMonth> tblPayrollMonths { get; set; }
    }
}
