//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDataReceiverErrorLog
    {
        public int DataReceiverErrorLogID { get; set; }
        public string Message { get; set; }
        public string Error { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
    }
}
