//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeAttendanceDetail
    {
        public int EmployeeAttendanceDetailID { get; set; }
        public Nullable<int> EmployeeAttendanceID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public int EmployeeTACode { get; set; }
        public System.DateTime LogTime { get; set; }
        public byte LogTimeType { get; set; }
        public string TerminalType { get; set; }
        public Nullable<int> TerminalID { get; set; }
        public string DeviceSerialNo { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public string EventType { get; set; }
        public string PunchType { get; set; }
        public string VerificationMode { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> reuid { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblEmployeeAttendance tblEmployeeAttendance { get; set; }
    }
}
