//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeDocument
    {
        public int EmployeeDocumentID { get; set; }
        public string DocumentName { get; set; }
        public string FileName { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
