//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeSalaryIncrement
    {
        public int EmployeeSalaryIncrementID { get; set; }
        public int EmployeeSalaryIncrementNo { get; set; }
        public System.DateTime EmployeeSalaryIncrementDate { get; set; }
        public int EffectiveMonth { get; set; }
        public int EffectiveYear { get; set; }
        public int EmployeeID { get; set; }
        public decimal CurrentBasicSalary { get; set; }
        public int IncrementType { get; set; }
        public decimal IncrementPercentage { get; set; }
        public decimal IncrementAmount { get; set; }
        public decimal NewBasicSalary { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> LastIncDate { get; set; }
        public Nullable<decimal> LastIncAmount { get; set; }
        public byte rState { get; set; }
        public int CompanyID { get; set; }
        public int FinPeriodID { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> reuid { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblFinPeriod tblFinPeriod { get; set; }
    }
}
