//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeOLD
    {
        public int EmployeeID { get; set; }
        public string EmployeeCode { get; set; }
        public int TACode { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeLastName { get; set; }
        public string EmployeeOtherName { get; set; }
        public string ImageFileName { get; set; }
        public byte Gender { get; set; }
        public int NationalityID { get; set; }
        public Nullable<System.DateTime> WorkVisaExpiryDate { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string POBoxNO { get; set; }
        public int CityID { get; set; }
        public string MpesaNo { get; set; }
        public string EmailID { get; set; }
        public Nullable<bool> Multicurrency { get; set; }
        public string IDNo { get; set; }
        public string NSSFNo { get; set; }
        public string NHIFNo { get; set; }
        public string PINNo { get; set; }
        public string PFNo { get; set; }
        public System.DateTime EmploymentEffectiveDate { get; set; }
        public byte EmploymentType { get; set; }
        public Nullable<System.DateTime> ContractExpiryDate { get; set; }
        public int EmployeeDepartmentID { get; set; }
        public int LocationID { get; set; }
        public int EmployeeDesignationID { get; set; }
        public int EmployeeWIBAClassID { get; set; }
        public int MinimumWageCategoryID { get; set; }
        public decimal DailyRate { get; set; }
        public decimal BasicSalary { get; set; }
        public decimal HousingAllowance { get; set; }
        public decimal WeekendAllowance { get; set; }
        public decimal AnnualLeaveBalance { get; set; }
        public byte PaymentMode { get; set; }
        public byte PayCycle { get; set; }
        public string BankAcNo { get; set; }
        public Nullable<int> BankNameID { get; set; }
        public Nullable<int> BankBranchID { get; set; }
        public bool IncomeType { get; set; }
        public int CurrencyID { get; set; }
        public int CompanyID { get; set; }
        public byte rstate { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<int> reuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
    }
}
