//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeServiceDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmployeeServiceDetail()
        {
            this.tblEmployees = new HashSet<tblEmployee>();
            this.tblEmployeeLeaveOpeningBalances = new HashSet<tblEmployeeLeaveOpeningBalance>();
        }
    
        public int EmployeeServiceDetailID { get; set; }
        public int EmployeeID { get; set; }
        public byte EmployeementStatus { get; set; }
        public System.DateTime EmploymentEffectiveDate { get; set; }
        public byte EmploymentType { get; set; }
        public Nullable<System.DateTime> ContractExpiryDate { get; set; }
        public int EmployeeDepartmentID { get; set; }
        public int LocationID { get; set; }
        public int EmployeeDesignationID { get; set; }
        public int EmployeeWIBAClassID { get; set; }
        public int MinimumWageCategoryID { get; set; }
        public decimal DailyRate { get; set; }
        public decimal BasicSalary { get; set; }
        public decimal HousingAllowance { get; set; }
        public decimal WeekendAllowance { get; set; }
        public byte EmployeeShiftType { get; set; }
        public Nullable<int> EmployeeShiftID { get; set; }
        public string ReinstatementReason { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public byte TerminationTypeID { get; set; }
        public string TerminationReason { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployee> tblEmployees { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblEmployeeDepartment tblEmployeeDepartment { get; set; }
        public virtual tblEmployeeDesignation tblEmployeeDesignation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeLeaveOpeningBalance> tblEmployeeLeaveOpeningBalances { get; set; }
        public virtual tblEmployeeShift tblEmployeeShift { get; set; }
        public virtual tblEmployeeWIBAClass tblEmployeeWIBAClass { get; set; }
        public virtual tblEmployementTerminationCause tblEmployementTerminationCause { get; set; }
        public virtual tblLocation tblLocation { get; set; }
        public virtual tblMinimumWageCategory tblMinimumWageCategory { get; set; }
    }
}
