//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeFamily
    {
        public int EmployeeFamilyID { get; set; }
        public int Relationship { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string POBoxNo { get; set; }
        public string City { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Beneficiary { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
