//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeAttendance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmployeeAttendance()
        {
            this.tblEmployeeAttendanceDetails = new HashSet<tblEmployeeAttendanceDetail>();
        }
    
        public int EmployeeAttendanceID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public Nullable<System.TimeSpan> InTime { get; set; }
        public Nullable<System.TimeSpan> OutTime { get; set; }
        public Nullable<int> EmployeeShiftID { get; set; }
        public Nullable<System.TimeSpan> ShiftStartTime { get; set; }
        public Nullable<System.TimeSpan> ShiftEndTime { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> reuid { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeAttendanceDetail> tblEmployeeAttendanceDetails { get; set; }
    }
}
