//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeShift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmployeeShift()
        {
            this.tblEmployeeServiceDetails = new HashSet<tblEmployeeServiceDetail>();
            this.tblEmployeeShiftAllocations = new HashSet<tblEmployeeShiftAllocation>();
        }
    
        public int EmployeeShiftID { get; set; }
        public string EmployeeShiftName { get; set; }
        public System.TimeSpan ShiftStartTime { get; set; }
        public System.TimeSpan ShiftEndTime { get; set; }
        public byte ShiftType { get; set; }
        public Nullable<System.TimeSpan> FirstBreakStartTime { get; set; }
        public Nullable<System.TimeSpan> FirstBreakEndTime { get; set; }
        public Nullable<System.TimeSpan> SecondBreakStartTime { get; set; }
        public Nullable<System.TimeSpan> SecondBreakEndTime { get; set; }
        public Nullable<System.TimeSpan> ThirdBreakStartTime { get; set; }
        public Nullable<System.TimeSpan> ThirdBreakEndTime { get; set; }
        public decimal NofWorkingHours { get; set; }
        public int CompanyID { get; set; }
        public byte rstate { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<int> reuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeServiceDetail> tblEmployeeServiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeShiftAllocation> tblEmployeeShiftAllocations { get; set; }
    }
}
