//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeLeaveOpeningBalance
    {
        public int EmployeeLeaveOpeningBalanceID { get; set; }
        public int EmployeeID { get; set; }
        public int EmployeeServiceDetailID { get; set; }
        public int LeaveTypeID { get; set; }
        public decimal LeaveOpeningBalance { get; set; }
        public int CompanyID { get; set; }
        public int FinPeriodID { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblEmployeeServiceDetail tblEmployeeServiceDetail { get; set; }
        public virtual tblFinPeriod tblFinPeriod { get; set; }
        public virtual tblLeaveType tblLeaveType { get; set; }
    }
}
