//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeShiftAllocation
    {
        public int EmployeeShiftAllocationID { get; set; }
        public int EmployeeID { get; set; }
        public int EmployeeShiftID { get; set; }
        public Nullable<System.DateTime> WEDateFrom { get; set; }
        public int CompanyID { get; set; }
        public int FinPeriodID { get; set; }
        public byte rstate { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<int> reuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblEmployeeShift tblEmployeeShift { get; set; }
        public virtual tblFinPeriod tblFinPeriod { get; set; }
    }
}
