//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmployee()
        {
            this.tblEmployeeAttendances = new HashSet<tblEmployeeAttendance>();
            this.tblEmployeeAttendanceDetails = new HashSet<tblEmployeeAttendanceDetail>();
            this.tblEmployeeDocuments = new HashSet<tblEmployeeDocument>();
            this.tblEmployeeFamilies = new HashSet<tblEmployeeFamily>();
            this.tblEmployeeLeaveOpeningBalances = new HashSet<tblEmployeeLeaveOpeningBalance>();
            this.tblPayrollEmployeeDetails = new HashSet<tblPayrollEmployeeDetail>();
            this.tblEmployeeRestDays = new HashSet<tblEmployeeRestDay>();
            this.tblEmployeeSalaryIncrements = new HashSet<tblEmployeeSalaryIncrement>();
            this.tblEmployeeServiceDetails = new HashSet<tblEmployeeServiceDetail>();
            this.tblEmployeeShiftAllocations = new HashSet<tblEmployeeShiftAllocation>();
            this.tblLeaveAdjustments = new HashSet<tblLeaveAdjustment>();
            this.tblLeaveApplications = new HashSet<tblLeaveApplication>();
            this.tblLeaveEncashments = new HashSet<tblLeaveEncashment>();
            this.tblLoanAdjustments = new HashSet<tblLoanAdjustment>();
            this.tblLoanApplications = new HashSet<tblLoanApplication>();
            this.tblSafariApplications = new HashSet<tblSafariApplication>();
            this.tblTAApprovals = new HashSet<tblTAApproval>();
        }
    
        public int EmployeeID { get; set; }
        public int EmployeeNoPrefixID { get; set; }
        public int EmployeeNo { get; set; }
        public int TACode { get; set; }
        public bool IsEmployeeInService { get; set; }
        public Nullable<int> EmployeeLastServiceDetailID { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeLastName { get; set; }
        public string EmployeeOtherName { get; set; }
        public string EmployeeImageFileName { get; set; }
        public byte Gender { get; set; }
        public int NationalityID { get; set; }
        public Nullable<System.DateTime> WorkVisaExpiryDate { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string POBoxNO { get; set; }
        public int CityID { get; set; }
        public string MpesaNo { get; set; }
        public string EmailID { get; set; }
        public bool Multicurrency { get; set; }
        public int EmployeeAccountingLedgerID { get; set; }
        public string IDNo { get; set; }
        public string NSSFNo { get; set; }
        public string NHIFNo { get; set; }
        public string PINNo { get; set; }
        public byte ProvidentFund { get; set; }
        public string PFNo { get; set; }
        public byte PaymentMode { get; set; }
        public byte PayCycle { get; set; }
        public string BankAcNo { get; set; }
        public Nullable<int> BankNameID { get; set; }
        public Nullable<int> BankBranchID { get; set; }
        public Nullable<int> BankCurrencyID { get; set; }
        public bool IncomeType { get; set; }
        public byte TAAttendanceType { get; set; }
        public byte TALatenessCharges { get; set; }
        public byte TAEarlyGoing { get; set; }
        public byte TAOvertime { get; set; }
        public byte TANegativeLeave { get; set; }
        public byte TAWeekendType { get; set; }
        public byte TAWeekEndAttendance { get; set; }
        public byte TAMissPunch { get; set; }
        public int CompanyID { get; set; }
        public byte rstate { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<int> reuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
    
        public virtual tblBankBranch tblBankBranch { get; set; }
        public virtual tblBankName tblBankName { get; set; }
        public virtual tblCity tblCity { get; set; }
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblCountry tblCountry { get; set; }
        public virtual tblCurrency tblCurrency { get; set; }
        public virtual tblEmployeeAccountingLedger tblEmployeeAccountingLedger { get; set; }
        public virtual tblEmployeeNoPrefix tblEmployeeNoPrefix { get; set; }
        public virtual tblEmployeeServiceDetail tblEmployeeServiceDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeAttendance> tblEmployeeAttendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeAttendanceDetail> tblEmployeeAttendanceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeDocument> tblEmployeeDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeFamily> tblEmployeeFamilies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeLeaveOpeningBalance> tblEmployeeLeaveOpeningBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPayrollEmployeeDetail> tblPayrollEmployeeDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeRestDay> tblEmployeeRestDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeSalaryIncrement> tblEmployeeSalaryIncrements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeServiceDetail> tblEmployeeServiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeShiftAllocation> tblEmployeeShiftAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeaveAdjustment> tblLeaveAdjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeaveApplication> tblLeaveApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeaveEncashment> tblLeaveEncashments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoanAdjustment> tblLoanAdjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoanApplication> tblLoanApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSafariApplication> tblSafariApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTAApproval> tblTAApprovals { get; set; }
    }
}
