//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFinPeriod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFinPeriod()
        {
            this.tblEmployeeLeaveOpeningBalances = new HashSet<tblEmployeeLeaveOpeningBalance>();
            this.tblEmployeeRestDays = new HashSet<tblEmployeeRestDay>();
            this.tblEmployeeSalaryIncrements = new HashSet<tblEmployeeSalaryIncrement>();
            this.tblEmployeeShiftAllocations = new HashSet<tblEmployeeShiftAllocation>();
            this.tblGridLayouts = new HashSet<tblGridLayout>();
            this.tblLeaveAdjustments = new HashSet<tblLeaveAdjustment>();
            this.tblLeaveApplications = new HashSet<tblLeaveApplication>();
            this.tblLeaveEncashments = new HashSet<tblLeaveEncashment>();
            this.tblLoanAdjustments = new HashSet<tblLoanAdjustment>();
            this.tblLoanApplications = new HashSet<tblLoanApplication>();
            this.tblPayrolls = new HashSet<tblPayroll>();
            this.tblSafariApplications = new HashSet<tblSafariApplication>();
            this.tblTAApprovals = new HashSet<tblTAApproval>();
        }
    
        public int FinPeriodID { get; set; }
        public string FinPeriodName { get; set; }
        public System.DateTime FinPeriodFrom { get; set; }
        public Nullable<System.DateTime> FinPeriodTo { get; set; }
        public int CompanyID { get; set; }
        public byte rstate { get; set; }
        public System.DateTime rcdt { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<int> reuid { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeLeaveOpeningBalance> tblEmployeeLeaveOpeningBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeRestDay> tblEmployeeRestDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeSalaryIncrement> tblEmployeeSalaryIncrements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeShiftAllocation> tblEmployeeShiftAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGridLayout> tblGridLayouts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeaveAdjustment> tblLeaveAdjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeaveApplication> tblLeaveApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeaveEncashment> tblLeaveEncashments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoanAdjustment> tblLoanAdjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoanApplication> tblLoanApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPayroll> tblPayrolls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSafariApplication> tblSafariApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTAApproval> tblTAApprovals { get; set; }
    }
}
