//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoliday
    {
        public int HolidayID { get; set; }
        public string HolidayName { get; set; }
        public byte HolidayType { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public bool RepeatOnSameDate { get; set; }
        public int TotalDays { get; set; }
        public string Remarks { get; set; }
        public byte rstate { get; set; }
        public int CompanyID { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> reuid { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
    }
}
