//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeaveType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLeaveType()
        {
            this.tblEmployeeLeaveOpeningBalances = new HashSet<tblEmployeeLeaveOpeningBalance>();
            this.tblLeaveAdjustments = new HashSet<tblLeaveAdjustment>();
            this.tblLeaveApplications = new HashSet<tblLeaveApplication>();
            this.tblLeaveEncashments = new HashSet<tblLeaveEncashment>();
        }
    
        public int LeaveTypeID { get; set; }
        public string LeaveTypeName { get; set; }
        public decimal AnnualEntitledDays { get; set; }
        public byte ApplicableTo { get; set; }
        public bool IsEncashable { get; set; }
        public bool CanCarryForward { get; set; }
        public bool IncludeWeekend { get; set; }
        public bool IncludePublicHoliday { get; set; }
        public byte Distribute { get; set; }
        public string Notes { get; set; }
        public int CompanyID { get; set; }
        public byte rstate { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> reuid { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeLeaveOpeningBalance> tblEmployeeLeaveOpeningBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeaveAdjustment> tblLeaveAdjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeaveApplication> tblLeaveApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeaveEncashment> tblLeaveEncashments { get; set; }
    }
}
