//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLocationWeekendSetting
    {
        public int LocationWeekendSetting { get; set; }
        public int LocationID { get; set; }
        public Nullable<System.DateTime> WEDateFrom { get; set; }
        public Nullable<System.DateTime> WEDateTo { get; set; }
        public byte Monday { get; set; }
        public byte Tuesday { get; set; }
        public byte Wednesday { get; set; }
        public byte Thursday { get; set; }
        public byte Friday { get; set; }
        public byte Saturday { get; set; }
        public byte Sunday { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> reuid { get; set; }
    
        public virtual tblLocation tblLocation { get; set; }
    }
}
