//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeaveApplicationDayDetail
    {
        public int LeaveApplicationDayDetailID { get; set; }
        public int LeaveApplicationID { get; set; }
        public System.DateTime LeaveDate { get; set; }
        public byte LeaveType { get; set; }
    
        public virtual tblLeaveApplication tblLeaveApplication { get; set; }
    }
}
