//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoanAdjustment
    {
        public int LoanAdjustmentID { get; set; }
        public int LoanAdjustmentNoPrefixID { get; set; }
        public int LoanAdjustmentNo { get; set; }
        public System.DateTime LoanAdjustmentDate { get; set; }
        public int EmployeeID { get; set; }
        public int LoanApplicationID { get; set; }
        public decimal LoanAdjustmentAmount { get; set; }
        public byte PaymentModeID { get; set; }
        public System.DateTime DateOfDeposite { get; set; }
        public Nullable<int> CompanyBankAccountID { get; set; }
        public string ReasonForLoanAdjustment { get; set; }
        public string Remarks { get; set; }
        public string ApplicationDocumentFileName { get; set; }
        public byte rstate { get; set; }
        public int CompanyID { get; set; }
        public int FinPeriodID { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> reuid { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblFinPeriod tblFinPeriod { get; set; }
        public virtual tblLoanAdjustmentNoPrefix tblLoanAdjustmentNoPrefix { get; set; }
        public virtual tblLoanApplication tblLoanApplication { get; set; }
    }
}
