//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoanApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLoanApplication()
        {
            this.tblLoanAdjustments = new HashSet<tblLoanAdjustment>();
        }
    
        public int LoanApplicationID { get; set; }
        public System.DateTime LoanApplicationDate { get; set; }
        public int LoanApplicationNoPrefixID { get; set; }
        public int LoanApplicationNo { get; set; }
        public int EmployeeID { get; set; }
        public decimal LoanAmount { get; set; }
        public int MonthFrom { get; set; }
        public int YearFrom { get; set; }
        public int MonthTo { get; set; }
        public int YearTo { get; set; }
        public int NofInstallment { get; set; }
        public decimal InstallmentAmount { get; set; }
        public string LoanPurpose { get; set; }
        public string Remarks { get; set; }
        public string ApplicationDocumentFileName { get; set; }
        public byte rstate { get; set; }
        public int CompanyID { get; set; }
        public int FinPeriodID { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> reuid { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblFinPeriod tblFinPeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoanAdjustment> tblLoanAdjustments { get; set; }
        public virtual tblLoanApplicationNoPrefix tblLoanApplicationNoPrefix { get; set; }
    }
}
