//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLocation()
        {
            this.tblEmployeeServiceDetails = new HashSet<tblEmployeeServiceDetail>();
            this.tblLocationWeekendSettings = new HashSet<tblLocationWeekendSetting>();
            this.tblUserGroupPermissionOnLocations = new HashSet<tblUserGroupPermissionOnLocation>();
        }
    
        public int LocationID { get; set; }
        public string LocationName { get; set; }
        public byte LocationTypeID { get; set; }
        public int GracePeriod { get; set; }
        public int CompanyID { get; set; }
        public byte rstate { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> reuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeServiceDetail> tblEmployeeServiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLocationWeekendSetting> tblLocationWeekendSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserGroupPermissionOnLocation> tblUserGroupPermissionOnLocations { get; set; }
    }
}
