//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeaveApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLeaveApplication()
        {
            this.tblLeaveApplicationDayDetails = new HashSet<tblLeaveApplicationDayDetail>();
        }
    
        public int LeaveApplicationID { get; set; }
        public int LeaveApplicationNoPrefixID { get; set; }
        public int LeaveApplicationNo { get; set; }
        public System.DateTime LeaveApplicationDate { get; set; }
        public int EmployeeID { get; set; }
        public int LeaveTypeID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public decimal NofLeaves { get; set; }
        public string Remarks { get; set; }
        public string ApplicationDocumentFileName { get; set; }
        public byte rstate { get; set; }
        public int CompanyID { get; set; }
        public int FinPeriodID { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> reuid { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblFinPeriod tblFinPeriod { get; set; }
        public virtual tblLeaveApplicationNoPrefix tblLeaveApplicationNoPrefix { get; set; }
        public virtual tblLeaveType tblLeaveType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeaveApplicationDayDetail> tblLeaveApplicationDayDetails { get; set; }
    }
}
