//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMinimumWageRate
    {
        public int MinimumWageRateID { get; set; }
        public int MinimumWageCategoryID { get; set; }
        public decimal MinimumWageCategoryUrbanRate { get; set; }
        public decimal MinimumWageCategoryRuralRate { get; set; }
        public Nullable<System.DateTime> WEDateFrom { get; set; }
        public Nullable<System.DateTime> WEDateTo { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> reuid { get; set; }
    
        public virtual tblMinimumWageCategory tblMinimumWageCategory { get; set; }
    }
}
