//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNonCashBenefit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNonCashBenefit()
        {
            this.tblPayrollEmployeeDetails = new HashSet<tblPayrollEmployeeDetail>();
        }
    
        public int NonCashBenefitID { get; set; }
        public string NonCashBenefitName { get; set; }
        public byte NonCashBenefitType { get; set; }
        public byte KRAValueType { get; set; }
        public decimal KRAValue { get; set; }
        public byte CostValueType { get; set; }
        public decimal CostValue { get; set; }
        public string VehicleType { get; set; }
        public string VehicleRegistrationNo { get; set; }
        public string VehicleMake { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleEnginePower { get; set; }
        public decimal EngineCCKRAValue { get; set; }
        public decimal VehicleCostKRAPerc { get; set; }
        public int CompanyID { get; set; }
        public byte rstate { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> reuid { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPayrollEmployeeDetail> tblPayrollEmployeeDetails { get; set; }
    }
}
