//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayrollEmployeeNonCashBenefit
    {
        public int PayrollEmployeeNonCashBenefitID { get; set; }
        public int PayrollEmployeeDetailID { get; set; }
        public int NonCashBenefitID { get; set; }
        public bool Recurring { get; set; }
        public decimal CostValue { get; set; }
        public decimal KRAPerc { get; set; }
        public decimal KRAValue { get; set; }
        public decimal KRAValueCalculatedOnAmt { get; set; }
    
        public virtual tblPayrollEmployeeDetail tblPayrollEmployeeDetail { get; set; }
    }
}
