//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPAYERelief
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPAYERelief()
        {
            this.tblPAYEReliefRates = new HashSet<tblPAYEReliefRate>();
            this.tblPayrollEmployePAYEReliefs = new HashSet<tblPayrollEmployePAYERelief>();
        }
    
        public int PAYEReliefID { get; set; }
        public string PAYEReliefName { get; set; }
        public bool Mandatory { get; set; }
        public byte PAYEReliefType { get; set; }
        public byte rstate { get; set; }
        public int CompanyID { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> reuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPAYEReliefRate> tblPAYEReliefRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPayrollEmployePAYERelief> tblPayrollEmployePAYEReliefs { get; set; }
        public virtual tblCompany tblCompany { get; set; }
    }
}
