//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSettingsL1
    {
        public int SettingL1ID { get; set; }
        public string SettingName { get; set; }
        public string SettingValueVC { get; set; }
        public Nullable<long> SettingValueLong { get; set; }
        public Nullable<int> SettingValueInt { get; set; }
        public Nullable<System.DateTime> SettingValueDateTime { get; set; }
        public Nullable<bool> SettingValueBoolean { get; set; }
        public Nullable<decimal> SettingValueDecimal { get; set; }
        public int CompanyID { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<int> reuid { get; set; }
    }
}
