//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSafariApplicationDayDetail
    {
        public int SafariApplicationDayDetailID { get; set; }
        public int SafariApplicationID { get; set; }
        public System.DateTime SafariDate { get; set; }
        public byte SafariType { get; set; }
    
        public virtual tblSafariApplication tblSafariApplication { get; set; }
    }
}
