//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaxSlabDetail
    {
        public int TaxSlabDetailID { get; set; }
        public int TaxSlabHeaderID { get; set; }
        public byte IncomeType { get; set; }
        public Nullable<decimal> TaxableValueFrom { get; set; }
        public Nullable<decimal> TaxableValueTo { get; set; }
        public Nullable<decimal> TaxValueEmployee { get; set; }
        public Nullable<decimal> TaxPercEmployee { get; set; }
        public Nullable<decimal> MaxTaxValueEmployee { get; set; }
        public Nullable<decimal> TaxValueEmployer { get; set; }
        public Nullable<decimal> TaxPercEmployer { get; set; }
        public Nullable<decimal> MaxTaxValueEmployer { get; set; }
    
        public virtual tblTaxSlabHeader tblTaxSlabHeader { get; set; }
    }
}
