//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTAApproval
    {
        public int TAApprovalID { get; set; }
        public int TAApprovalNoPrefixID { get; set; }
        public int TAApprovalNo { get; set; }
        public System.DateTime TAApprovalDate { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime ApprovedDate { get; set; }
        public byte ApprovalTypeID { get; set; }
        public decimal ApprovedHours { get; set; }
        public string Remarks { get; set; }
        public string ApplicationDocumentFileName { get; set; }
        public byte rstate { get; set; }
        public int CompanyID { get; set; }
        public int FinPeriodID { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> reuid { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblFinPeriod tblFinPeriod { get; set; }
        public virtual tblTAApprovalNoPrefix tblTAApprovalNoPrefix { get; set; }
    }
}
