//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool SuperAdmin { get; set; }
        public int UserGroupID { get; set; }
        public string EMailID { get; set; }
        public byte rstate { get; set; }
        public System.DateTime rcdt { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<int> reuid { get; set; }
    
        public virtual tblUserGroup tblUserGroup { get; set; }
    }
}
