//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vision.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserGroupPermissionOnLocation
    {
        public int UserGroupPermissionOnLocationID { get; set; }
        public int LocationID { get; set; }
        public int UserGroupID { get; set; }
    
        public virtual tblLocation tblLocation { get; set; }
        public virtual tblUserGroup tblUserGroup { get; set; }
    }
}
